version: 2.1
parameters:
  vmanage_host:
    type: string
    default: $VMANAGE
  vmanage_user:
    type: string
    default: $J_USERNAME
  vmanage_pass:
    type: string
    default: $J_PASSWORD
orbs:
  newman: oshafran/oshafran-pied-piper-orb@dev:alpha
jobs:
  "Checkout":
    resource_class: "small"
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: /root/project
          paths:
            - ./*
workflows:
  default-pipeline:
    jobs:
      - "Checkout"
      - newman/pipeline:
          dir: /root/project/collections
          openapiDir: /root/project/openapi
          vManageIP: << pipeline.parameters.vmanage_host >>
          vManageUser: << pipeline.parameters.vmanage_user >>
          vManagePwd: << pipeline.parameters.vmanage_pass >>
          requires: 
            - "Checkout"
