version: 2.1
orbs:
  newman: oshafran/oshafran-pied-piper-orb@dev:alpha
jobs:
  "Checkout":
    resource_class: "small"
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: /root/project
          paths:
            - ./*
workflows:
  default-pipeline:
    jobs:
      - "Checkout"
      - newman/pipeline:
          dir: /root/project/collections
          openapiDir: /root/project/openapi
          vManageIP:
            type: env_var_name
            default: VMANAGEIP
          requires: 
            - "Checkout"

